### ISSUE TITLE
ctrl + p does not work

### ISSUE THREAD

**Issue by gforceg** [chaliy/vscode-handlebars-preview#11]
Hello,

When I enable the extension ctrl + p the quick open feature does not work. When I disable the extension the quick open feature works.

I didn't know that an extension was causing this problem until I found this issue: https://github.com/Microsoft/vscode/issues/72647

**Comment by justinforce** [comment]
Please don't add chords using extremely common keyboard shortcuts. Ctrl+P is incredibly important to many VSCode users. It's even suggested by the editor when no files are open.

![image](https://user-images.githubusercontent.com/324632/64366196-8f896380-cfca-11e9-86ae-f79f72ed4984.png)

Thanks!

**Comment by samusstrike** [comment]
I recommend to change the package.json file to have a different keybinding:
Instead of: "key": "ctrl+p h"
Use: "key": "ctrl+k h"

```json
{
    "keybindings": [{
      "command": "handlebarsPreview.preview",
      "key": "ctrl+k h",
      "when": "!terminalFocus"
    }]
}
```
I suppose I could create a pull request.

An interim solution for anyone seeing this is to update your keybindings manually to "Ctrl+K H".
1. You can get to your key bindings using the file menu or the shortcut "Ctrl + K Ctrl+S".
2. Search for the text "ctrl p" and you will see the binding for Handlebars.
3. Change it to "Ctrl+K H" or whatever suits you.

**Comment by dmrickey** [comment]
Why is this still the default shortcut in this extension when it's overwriting a default shortcut in the editor?

**Comment by chaliy** [comment]
@dmrickey , @samusstrike and others. Now extension uses `ctrl+k h`, thank you for contribution.
